language: crystal
crystal:
  - latest
  - nightly
script:
  - crystal spec
  - crystal docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: markov
  on:
    branch: master
  local_dir: docs
